export default {
  ADD_TODO         : 'ADD_TODO',
  DELETE_TODO      : 'DELETE_TODO',
  EDIT_TODO        : 'EDIT_TODO',
  COMPLETE_TODO    : 'COMPLETE_TODO',
  COMPLETE_ALL     : 'COMPLETE_ALL',
  CLEAR_COMPLETED  : 'CLEAR_COMPLETED',
  LOGIN_SUCCESS    : 'LOGIN_SUCCESS',
  LOGIN_FAILED     : 'LOGIN_FAILED',
  LOGOUT_SUCCESS   : 'LOGOUT_SUCCESS',
  LOGOUT_FAILED    : 'LOGOUT_FAILED',
};
